spring:
  application:
    name: '@project.name@'
  redis:
    host: 0.0.0.0
    port: 55000
    password: redispw
app:
  job:
    cron:
      product-job: 0 0 0,21 ? * * *
      position-job:
  stream:
    key:
    group:
  integration:
    kazan:
      token:
    styx: