spring:
  application:
    name: '@project.name@'
  redis:
    host: 0.0.0.0
    port: 55000
    password: redispw
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 30
            class: org.quartz.simpl.SimpleThreadPool
          jobStore:
            misfireThreshold: 60000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
            useProperties: true
    jdbc:
      initialize-schema: never
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/ke-scrapper
    username: postgres
    password: 5053
    hikari:
      minimum-idle: 5
      maximum-pool-size: 12
app:
  aws-stream:
    endpoint: 'yds.serverless.yandexcloud.net'
    accessKey: fake-access-key
    secretKey: fake-secret-key
    region: ru-central-1
    ke-stream:
      name: '/ru-central1/b1gtojcphtuae1n9siie/etnvck8jo3kuh0vilc57/ke-stream'
  job:
    cron:
      delete-product-cache: 0 0/59 * * * ?
      position-product-job: 0 0 0,21 ? * * *
      product-job: 0 0 0,21 ? * * *
      position-job: 0 0 4 ? * * *
      category-job: 0 0 1 ? * * *
      trim-job: 0 0/60 * * * ?
      clean-position-jobs: 0 0 15 ? * * *
  stream:
    product:
      key: ke-product-stream
      group: ke-product-group
      maxlen: 50000
      waitPending: 0
    position:
      key: ke-position-stream
      group: ke-position-group
      maxlen: 50000
      waitPending: 0
    category:
      key: ke-category-stream
      group: ke-category-group
      maxlen: 50000
      waitPending: 0
  integration:
    timeout:
      from: 1000
      to: 3750
    kazan:
      token:
    styx:

loki:
  host: localhost
  enabled: false

redis:
  local: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  metrics:
    export:
      prometheus:
        enabled: true